# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: demo
    github:
      owner: golang-ws
      name: homebrew-demo
    folder: Formula
    homepage: "https://github.com/jenkins-zh/jenkins-cli"
    description: Jenkins CLI allows you manage your Jenkins as an easy way
    test: |
      version_output = shell_output("#{bin}/jcli version")
      assert_match version.to_s, version_output
    install: |
      bin.install name

      # Install bash completion
      output = Utils.popen_read("#{bin}/jcli completion")
      (bash_completion/"jcli").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/jcli completion --type zsh")
      (zsh_completion/"_jcli").write output

      prefix.install_metafiles
